name: istio-go

on:
  push:
    tags:
     - 'v*.*.*'
jobs:
  image-push:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Set env
       run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.CR_PAT }}
     - name: Build and Push
       uses: docker/build-push-action@v2
       id: docker_build
       with:
         context: .
         file: ./employeeV1/Dockerfile
         push: true
         tags: |
           ghcr.io/${{ github.repository_owner }}/employeev1:latest
           ghcr.io/${{ github.repository_owner }}/employeev1:${{ env.RELEASE_VERSION }}
