name: istio-go

on:
  push:
    branches: [ main ]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
       path: ./employeeV1
     - name: set up go
       uses: actions/setup-go@v1
       with:
         go-version: '1.16.3'
     - name: go mod download
       run: go 
     - name: build
       run: go build -v ./main.go
