name: istio-go

on:
  push:
    branches: [ main ]
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v1
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v1
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.CR_PAT }}
     - name: Build and Push
       uses: docker/build-push-action@v2
       id: docker_build
       working-directory: ./employeeV1
       with:
         context: .
         file: ./Dockerfile
         push: true
         tags: |
           ghcr.io/${{ github.repository_owner }}/employeeV1:latest
           ghcr.io/${{ github.repository_owner }}/employeeV1:${{ env.RELEASE_VERSION }}
